FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Dependências do sistema para pyodbc + (opcional) FreeTDS
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    unixodbc \
    unixodbc-dev \
    gcc \
    g++ \
    freetds-dev \
    freetds-bin \
    tdsodbc \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]